
    const GET_ALLGAMES = 'GET_ALLGAMES';
    const GET_GENRES = 'GET_GENRES';
    const GET_GAMEBYID = 'GET_GAMEBYID';
    const GET_PLATFORMS = 'GET_PLATFORMS';
    const FILTER_GENRES = "FILTER_GENRES";
    const FILTER_GAMES = "FILTER_GAMES";
    const FILTER_ORDER = "FILTER_ORDER";
    const ONSEARCH = "ONSEARCH";
    const FILTER_RATING = "FILTER_RATING"
  

    export {GET_ALLGAMES , GET_GENRES,GET_GAMEBYID,
        GET_PLATFORMS,FILTER_GENRES,FILTER_GAMES,FILTER_ORDER, ONSEARCH,FILTER_RATING}



