
    const GET_ALLGAMES = 'GET_ALLGAMES';
    const GET_GENRES = 'GET_GENRES';
    const GET_GAMEBYID = 'GET_GAMEBYID';
    const GET_PLATFORMS = 'GET_PLATFORMS';

    export {GET_ALLGAMES , GET_GENRES,GET_GAMEBYID,GET_PLATFORMS}



